services:
  db:
    image: postgres:18.4@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"

  prestart:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?connect_timeout=${DB_CONNECT_TIMEOUT:-10}

  backend:
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?connect_timeout=${DB_CONNECT_TIMEOUT:-10}
    ports:
      - "8000:8000"
    command:
      - fastapi
      - run
      - --reload
      - app/main.py
    develop:
      watch:
        - path: ../self-checkout-backend
          action: sync
          target: /app/backend
          ignore:
            - ../self-checkout-backend/.venv
            - .venv
        - path: ../self-checkout-backend/pyproject.toml
          action: rebuild
    volumes:
      - ../self-checkout-backend/htmlcov:/app/backend/htmlcov

  admin:
    restart: "no"
    ports:
      - "5173:80"

  ml:
    restart: "no"
    ports:
      - "8001:8000"
    command:
      - fastapi
      - run
      - --reload
      - app/main.py
    develop:
      watch:
        - path: ../self-checkout-ml
          action: sync
          target: /app

volumes:
  app-db-data:
